### PR TITLE
[bugfix] Fix global hotkeys not working on startup

### LINKED ISSUE #318: Global Media Keys not working
## Current Behavior

Global Media Keys not working until global media key option is toggled off and back on. 

## Steps to Reproduce

1.  Launch Feishin - try to use media keys - nothing happens
 
2.  Go into options and toggle global media key off and back on

## Possible Solution (Not obligatory)

Toggling the setting off and on seems to work but only for 1 launch.

## Context

Trying to set up  my media keys to work with Feishin.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.1
-   Operating System and version (e.g. Windows 10) : Win 11
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome  0.49.3
-   Node version (if developing locally) :

### PR DESCRIPTION
**Pull request by iiPythonx**
Fixes #318, #404, and #477 which was caused just by a broken comparison. Not sure why the value is `undefined` when it's set to `true`, but    at least now the statements are consistent and global hotkeys work on startup.

(tested and working, if it doesn't work then maybe theres a deeper issue, not sure)

### CODE REVIEW

File: src/main/main.ts [hunk 1]
```diff
@@ -635,7 +635,7 @@ ipcMain.on(
 
         const globalMediaKeysEnabled = store.get('global_media_hotkeys') as boolean;
 
-        if (globalMediaKeysEnabled) {
+        if (globalMediaKeysEnabled !== false) {
```
Comment (kgarner7) [inline src/main/main.ts]: Rather than changing the condition, a potentially more clear option would be `store.get('global_media_hotkeys', true) as boolean` (`true` being the default when not defined).

Comment (iiPythonx) [reply src/main/main.ts]: I didn't know that was a thing, I'll definitely use that instead to clear up the code.

**Comment by iiPythonx** [comment]
That should do it, testing shows that it still works and I'm not sure of any other improvements to make to it.

**Comment by kgarner7** [comment]
Thanks!
